#!/bin/sh

echo " "
echo "//-----------------------------//"
echo "Running formatter for Rust code"
echo "//-----------------------------//"
echo " "
cargo fmt
git add -A
echo "\033[0;32mFormatting done...\033[0m"
echo " "

echo "//-----------------------------//"